### PR TITLE
Added connection monitor that polls the socket to see if the client lost the connection.

### PR DESCRIPTION
**Pull request by microm8**
Polling is done same way as IsConnected in https://github.com/aquamoth/SocketMessaging/blob/master/SocketMessaging/Connection.cs

### CODE REVIEW

**Comment by jchristn** [comment]
Hi @microm8 thanks for contributing this!  By chance have you tested on each of the various frameworks?  Nice work, it looks very clean and easy to understand!

**Comment by microm8** [comment]
I didn't think of the various frameworks. I have tested in a .NET 6 application and ran the unit tests...

**Comment by tinohager** [comment]
Code source: https://stackoverflow.com/a/6993334/6097503

**Comment by microm8** [comment]
Hi Tino, the code snippet can be found multiple places. I have not idea who the original author is. As mentioned I found it here:
https://github.com/aquamoth/SocketMessaging/blob/master/SocketMessaging/Connection.cs

**Comment by jchristn** [comment]
Thank you @microm8 - just merged and published to NuGet!  https://www.nuget.org/packages/SuperSimpleTcp/2.6.0.6  
Also added you to the README.  Thank you for your contribution!

**Pull request merged**
